version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=skillswap.settings
    stdin_open: true
    tty: true
    command: /app/docker-entrypoint.sh
